[[pages]]
path = "dashboard/main.py"
name = "Project description"
icon = "ğŸ’»"

[[pages]]
path = "dashboard/pages/page_houses.py"
name = "Houses"
icon = "ğŸ¡"

[[pages]]
path = "dashboard/pages/page_lands.py"
name = "Houses"
icon = "ğŸŒ³"

[[pages]]
path = "dashboard/pages/page_apartments.py"
name = "Houses"
icon = "ğŸ¢"
